adj1 = input("Adjective: ")
adj2 = input("Adjective: ")
noun1 = input("Noun: ")
adj3 = input("Adjective: ")
ap = input("A Place: ")
noun2 = input("Noun: ")
pn1 = input("Plural Noun: ")
pn2 = input("Plural Noun: ")
adverb = input("Adverb: ")
noun3 = input("Noun: ")
adj4 = input("Adjective: ")
verb1 = input("Verb: ")
verb2 = input("Verb: ")
adj5 = input("Adjective: ")
adj6 = input("Adjective: ")
pn3 = input("Plural Noun: ")
noun4 = input("Noun: ")

madlib = f"Ho, ho, ho, {adj1} blog fans! Santa here. It's crunch time at my {adj2} workshop, and everyone is as busy as a/an {noun1}. I've received tons of {adj3} letters from girls and boys around (the) {ap}, and elves have been working around the {noun2} to make all of their {pn1}. Plus, I've finally finished putting together the list of naughty {pn2}, which I'm {adverb} happy to say is much shorter than last year's! As I look out the {noun3}, I can see the reindeer are groomed and look really {adj4}, and my sleigh is polished and ready to {verb1}. I will be able to {verb2} though the {adj5} night sky as soon as Mrs. Claus finishes letting out my {adj6} red suit. I'm sorry to say, I ate a few to many {pn3} this past year! See you soon! Your {noun4}, Santa"
print(madlib)